 name: Update Number

on:
  repository_dispatch:
    types: [update_number]

jobs:
  update-number:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update JSON
      run: |
        # Install jq JSON processor
        sudo apt-get install jq
        
        # Update currentNumber
        jq --arg number "${{ github.event.client_payload.number }}" '.currentNumber = ($number | tonumber)' data/content.json > temp.json
        mv temp.json data/content.json

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/content.json
        git commit -m "Update current number to ${{ github.event.client_payload.number }}"
        git push
